In [39]:
# Importing necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import f1_score, accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.inspection import permutation_importance
from imblearn.over_sampling import SMOTE
import mplfinance as mpf
import matplotlib.dates as mdates
import matplotlib.ticker as mticker
from mplfinance.original_flavor import candlestick_ohlc
from statsmodels.tsa.arima_model import ARIMA
from sklearn.metrics import mean_squared_error
import seaborn as sns
from finta import TA
import backtrader as bt
from backtesting import Backtest, Strategy
from backtesting.lib import crossover, SignalStrategy, TrailingStrategy

In [ ]:
pip install openpyxl

In [40]:
## loading file

df = pd.read_csv(r"C:\Users\ganes\OneDrive\Desktop\capestone\BTC_training_data_2024-01-01_to_2024-08-31.csv")

In [41]:
import talib
import pandas as pd

# Assuming you already have a DataFrame 'df' with a 'close' column

# Calculating SMAs using TA-Lib
df['SMA_2'] = talib.SMA(df['close'], timeperiod=2)    # 2-period SMA
df['SMA_5'] = talib.SMA(df['close'], timeperiod=5)    # 5-period SMA
df['SMA_10'] = talib.SMA(df['close'], timeperiod=10)  # 10-period SMA
df['SMA_15'] = talib.SMA(df['close'], timeperiod=15)  # 15-period SMA
df['SMA_20'] = talib.SMA(df['close'], timeperiod=20)  # 20-period SMA
df['SMA_50'] = talib.SMA(df['close'], timeperiod=50)  # 50-period SMA

# Calculating SMAs using TA-Lib
df['EMA_2'] = talib.EMA(df['close'], timeperiod=2)    # 2-period EMA
df['EMA_5'] = talib.EMA(df['close'], timeperiod=5)    # 5-period EMA
df['EMA_10'] = talib.EMA(df['close'], timeperiod=10)  # 10-period EMA
df['EMA_15'] = talib.EMA(df['close'], timeperiod=15)  # 15-period EMA
df['EMA_20'] = talib.EMA(df['close'], timeperiod=20)  # 20-period EMA
df['EMA_50'] = talib.EMA(df['close'], timeperiod=50)  # 50-period EMA


# Displaying the DataFrame with the moving averages
df.head(20)

,unix,date,symbol,open,high,low,close,volume,volume_from,marketorder_volume,...,SMA_10,SMA_15,SMA_20,SMA_50,EMA_2,EMA_5,EMA_10,EMA_15,EMA_20,EMA_50
0,1704067260000,2024-01-01 00:01:00,BTCUSDT,42298.62,42320.00,42298.61,42320.00,21.16779,8.955809e+05,13.47483,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1704067320000,2024-01-01 00:02:00,BTCUSDT,42319.99,42331.54,42319.99,42325.50,21.60391,9.143711e+05,11.21801,...,NaN,NaN,NaN,NaN,42322.750000,NaN,NaN,NaN,NaN,NaN
2,1704067380000,2024-01-01 00:03:00,BTCUSDT,42325.50,42368.00,42325.49,42367.99,30.50730,1.291997e+06,24.04878,...,NaN,NaN,NaN,NaN,42352.910000,NaN,NaN,NaN,NaN,NaN
3,1704067440000,2024-01-01 00:04:00,BTCUSDT,42368.00,42397.23,42367.99,42397.23,46.05107,1.951945e+06,34.12804,...,NaN,NaN,NaN,NaN,42382.456667,NaN,NaN,NaN,NaN,NaN
4,1704067500000,2024-01-01 00:05:00,BTCUSDT,42397.22,42409.20,42385.26,42409.20,32.26766,1.368040e+06,20.99093,...,NaN,NaN,NaN,NaN,42400.285556,42363.984000,NaN,NaN,NaN,NaN
5,1704067560000,2024-01-01 00:06:00,BTCUSDT,42409.19,42431.09,42405.89,42423.95,28.13597,1.193372e+06,15.57884,...,NaN,NaN,NaN,NaN,42416.061852,42383.972667,NaN,NaN,NaN,NaN
6,1704067620000,2024-01-01 00:07:00,BTCUSDT,42423.94,42432.74,42414.45,42414.45,26.49738,1.124163e+06,6.62244,...,NaN,NaN,NaN,NaN,42414.987284,42394.131778,NaN,NaN,NaN,NaN
7,1704067680000,2024-01-01 00:08:00,BTCUSDT,42414.45,42420.07,42406.00,42420.07,28.00823,1.187956e+06,18.05296,...,NaN,NaN,NaN,NaN,42418.375761,42402.777852,NaN,NaN,NaN,NaN
8,1704067740000,2024-01-01 00:09:00,BTCUSDT,42420.06,42420.07,42403.99,42409.96,26.40178,1.119844e+06,8.20639,...,NaN,NaN,NaN,NaN,42412.765254,42405.171901,NaN,NaN,NaN,NaN
9,1704067800000,2024-01-01 00:10:00,BTCUSDT,42409.97,42440.06,42409.96,42440.05,22.61788,9.596811e+05,19.13842,...,42392.840,NaN,NaN,NaN,42430.955085,42416.797934,42392.840000,NaN,NaN,NaN
10,1704067860000,2024-01-01 00:11:00,BTCUSDT,42440.06,42480.68,42440.05,42479.32,31.81488,1.350940e+06,21.44103,...,42408.772,NaN,NaN,NaN,42463.198362,42437.638623,42408.563636,NaN,NaN,NaN
11,1704067920000,2024-01-01 00:12:00,BTCUSDT,42479.31,42479.32,42462.22,42462.24,25.25342,1.072439e+06,5.84846,...,42422.446,NaN,NaN,NaN,42462.559454,42445.839082,42418.322975,NaN,NaN,NaN
12,1704067980000,2024-01-01 00:13:00,BTCUSDT,42462.24,42480.16,42460.00,42480.15,21.40862,9.091495e+05,13.69327,...,42433.662,NaN,NaN,NaN,42474.286485,42457.276055,42429.564252,NaN,NaN,NaN
13,1704068040000,2024-01-01 00:14:00,BTCUSDT,42480.16,42488.09,42465.78,42488.00,34.04769,1.446176e+06,13.13848,...,42442.739,NaN,NaN,NaN,42483.428828,42467.517370,42440.188934,NaN,NaN,NaN
14,1704068100000,2024-01-01 00:15:00,BTCUSDT,42488.00,42516.46,42482.47,42510.00,33.40445,1.419584e+06,22.96846,...,42452.819,42423.207333,NaN,NaN,42501.142943,42481.678246,42452.881855,42423.207333,NaN,NaN
15,1704068160000,2024-01-01 00:16:00,BTCUSDT,42510.01,42554.57,42510.00,42541.27,61.90631,2.633519e+06,38.74330,...,42464.551,42437.958667,NaN,NaN,42527.894314,42501.542164,42468.952427,42437.965167,NaN,NaN
16,1704068220000,2024-01-01 00:17:00,BTCUSDT,42541.27,42541.27,42503.36,42503.36,27.71049,1.178139e+06,5.71349,...,42473.442,42449.816000,NaN,NaN,42511.538105,42502.148110,42475.208349,42446.139521,NaN,NaN
17,1704068280000,2024-01-01 00:18:00,BTCUSDT,42503.36,42503.37,42467.28,42474.03,25.78878,1.095530e+06,10.09214,...,42478.838,42456.885333,NaN,NaN,42486.532702,42492.775406,42474.994104,42449.625831,NaN,NaN
18,1704068340000,2024-01-01 00:19:00,BTCUSDT,42474.03,42476.50,42458.58,42458.85,14.51538,6.164576e+05,5.29852,...,42483.727,42460.993333,NaN,NaN,42468.077567,42481.466938,42472.058812,42450.778852,NaN,NaN
19,1704068400000,2024-01-01 00:20:00,BTCUSDT,42458.85,42465.48,42458.28,42459.31,19.02752,8.079456e+05,10.04046,...,42485.653,42464.334000,42439.2465,NaN,42462.232522,42474.081292,42469.740846,42451.845245,42439.2465,NaN

In [42]:
df.tail()

,unix,date,symbol,open,high,low,close,volume,volume_from,marketorder_volume,...,SMA_10,SMA_15,SMA_20,SMA_50,EMA_2,EMA_5,EMA_10,EMA_15,EMA_20,EMA_50
316575,1725062100000,2024-08-30 23:55:00,BTCUSDT,59157.00,59157.0,59134.40,59138.00,6.09917,360704.671503,2.74285,...,59140.088,59130.837333,59133.0980,59166.1320,59144.773517,59148.740478,59144.452365,59143.624459,59145.433076,59159.895219
316576,1725062160000,2024-08-30 23:56:00,BTCUSDT,59138.00,59140.0,59121.10,59121.10,4.19129,247846.584773,0.66468,...,59140.550,59131.390000,59129.9030,59164.0986,59128.991172,59139.526985,59140.206481,59140.808902,59143.115640,59158.373838
316577,1725062220000,2024-08-30 23:57:00,BTCUSDT,59121.10,59121.1,59119.26,59119.27,1.23603,73073.298145,0.30333,...,59141.776,59130.872667,59128.2060,59161.8850,59122.510391,59132.774657,59136.399848,59138.116539,59140.844627,59156.840354
316578,1725062280000,2024-08-30 23:58:00,BTCUSDT,59119.27,59140.0,59117.43,59117.43,9.53179,563601.204274,2.03406,...,59141.819,59132.434667,59128.0225,59159.6936,59119.123464,59127.659771,59132.950784,59135.530722,59138.614662,59155.294850
316579,1725062340000,2024-08-30 23:59:00,BTCUSDT,59117.44,59124.0,59114.42,59123.99,8.10414,479085.670595,5.51428,...,59141.925,59132.445333,59128.2720,59158.0948,59122.367821,59126.436514,59131.321551,59134.088131,59137.221837,59154.067209

In [43]:
df['date'] = pd.to_datetime(df['date'])

# Setting 'datetime' as the index
df.set_index('date', inplace=True)
df.head()

,unix,symbol,open,high,low,close,volume,volume_from,marketorder_volume,marketorder_volume_from,...,SMA_10,SMA_15,SMA_20,SMA_50,EMA_2,EMA_5,EMA_10,EMA_15,EMA_20,EMA_50
date,,,,,,,,,,,,,,,,,,,,,
2024-01-01 00:01:00,1704067260000,BTCUSDT,42298.62,42320.00,42298.61,42320.00,21.16779,8.955809e+05,13.47483,5.700808e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01-01 00:02:00,1704067320000,BTCUSDT,42319.99,42331.54,42319.99,42325.50,21.60391,9.143711e+05,11.21801,4.747986e+05,...,NaN,NaN,NaN,NaN,42322.750000,NaN,NaN,NaN,NaN,NaN
2024-01-01 00:03:00,1704067380000,BTCUSDT,42325.50,42368.00,42325.49,42367.99,30.50730,1.291997e+06,24.04878,1.018449e+06,...,NaN,NaN,NaN,NaN,42352.910000,NaN,NaN,NaN,NaN,NaN
2024-01-01 00:04:00,1704067440000,BTCUSDT,42368.00,42397.23,42367.99,42397.23,46.05107,1.951945e+06,34.12804,1.446539e+06,...,NaN,NaN,NaN,NaN,42382.456667,NaN,NaN,NaN,NaN,NaN
2024-01-01 00:05:00,1704067500000,BTCUSDT,42397.22,42409.20,42385.26,42409.20,32.26766,1.368040e+06,20.99093,8.899445e+05,...,NaN,NaN,NaN,NaN,42400.285556,42363.984,NaN,NaN,NaN,NaN

In [44]:
df.tail()

,unix,symbol,open,high,low,close,volume,volume_from,marketorder_volume,marketorder_volume_from,...,SMA_10,SMA_15,SMA_20,SMA_50,EMA_2,EMA_5,EMA_10,EMA_15,EMA_20,EMA_50
date,,,,,,,,,,,,,,,,,,,,,
2024-08-30 23:55:00,1725062100000,BTCUSDT,59157.00,59157.0,59134.40,59138.00,6.09917,360704.671503,2.74285,162205.510487,...,59140.088,59130.837333,59133.0980,59166.1320,59144.773517,59148.740478,59144.452365,59143.624459,59145.433076,59159.895219
2024-08-30 23:56:00,1725062160000,BTCUSDT,59138.00,59140.0,59121.10,59121.10,4.19129,247846.584773,0.66468,39305.691885,...,59140.550,59131.390000,59129.9030,59164.0986,59128.991172,59139.526985,59140.206481,59140.808902,59143.115640,59158.373838
2024-08-30 23:57:00,1725062220000,BTCUSDT,59121.10,59121.1,59119.26,59119.27,1.23603,73073.298145,0.30333,17932.648169,...,59141.776,59130.872667,59128.2060,59161.8850,59122.510391,59132.774657,59136.399848,59138.116539,59140.844627,59156.840354
2024-08-30 23:58:00,1725062280000,BTCUSDT,59119.27,59140.0,59117.43,59117.43,9.53179,563601.204274,2.03406,120269.592152,...,59141.819,59132.434667,59128.0225,59159.6936,59119.123464,59127.659771,59132.950784,59135.530722,59138.614662,59155.294850
2024-08-30 23:59:00,1725062340000,BTCUSDT,59117.44,59124.0,59114.42,59123.99,8.10414,479085.670595,5.51428,325980.384113,...,59141.925,59132.445333,59128.2720,59158.0948,59122.367821,59126.436514,59131.321551,59134.088131,59137.221837,59154.067209

In [45]:
# Creating RSI for different time periods

# Calculating RSI for scalping (7-period)
df['RSI_7'] = talib.RSI(df['close'], timeperiod=7)

# Calculating RSI for day trading (14-period)
df['RSI_14'] = talib.RSI(df['close'], timeperiod=14)

# Calculating RSI for swing trading (21-period)
df['RSI_21'] = talib.RSI(df['close'], timeperiod=21)

# Displaying the DataFrame with the new RSI columns
df[['close', 'RSI_7', 'RSI_14', 'RSI_21']].head(n=10)

                        close      RSI_7  RSI_14  RSI_21
date
2024-01-01 00:01:00  42320.00        NaN     NaN     NaN
2024-01-01 00:02:00  42325.50        NaN     NaN     NaN
2024-01-01 00:03:00  42367.99        NaN     NaN     NaN
2024-01-01 00:04:00  42397.23        NaN     NaN     NaN
2024-01-01 00:05:00  42409.20        NaN     NaN     NaN
2024-01-01 00:06:00  42423.95        NaN     NaN     NaN
2024-01-01 00:07:00  42414.45        NaN     NaN     NaN
2024-01-01 00:08:00  42420.07  92.021500     NaN     NaN
2024-01-01 00:09:00  42409.96  83.727505     NaN     NaN
2024-01-01 00:10:00  42440.05  87.606276     NaN     NaN

In [46]:
# Calculating MACD with adjusted periods (e.g., 7, 21, 5)
df['MACD'], df['MACD_Signal'], df['MACD_Hist'] = talib.MACD(df['close'], fastperiod=7, slowperiod=21, signalperiod=5)

# Displaying the DataFrame with MACD, Signal Line, and Histogram columns
df[['close', 'MACD', 'MACD_Signal', 'MACD_Hist']].tail()

                        close      MACD  MACD_Signal  MACD_Hist
date
2024-08-30 23:55:00  59138.00  0.976693    -1.947231   2.923924
2024-08-30 23:56:00  59121.10 -3.221437    -2.371967  -0.849471
2024-08-30 23:57:00  59119.27 -6.301721    -3.681885  -2.619836
2024-08-30 23:58:00  59117.43 -8.551420    -5.305063  -3.246357
2024-08-30 23:59:00  59123.99 -8.847319    -6.485815  -2.361504

In [47]:
# Bollinger Bands with 10 periods and 1.5 standard deviations
df['upper_band_10_1_5'], df['middle_band_10_1_5'], df['lower_band_10_1_5'] = talib.BBANDS(
    df['close'], timeperiod=10, nbdevup=1.5, nbdevdn=1.5, matype=1)

# Bollinger Bands with 10 periods and 2 standard deviations
df['upper_band_10_2'], df['middle_band_10_2'], df['lower_band_10_2'] = talib.BBANDS(
    df['close'], timeperiod=10, nbdevup=2, nbdevdn=2, matype=1)

# Bollinger Bands with 20 periods and 1.5 standard deviations
df['upper_band_20_1_5'], df['middle_band_20_1_5'], df['lower_band_20_1_5'] = talib.BBANDS(
    df['close'], timeperiod=20, nbdevup=1.5, nbdevdn=1.5, matype=1)

# Bollinger Bands with 20 periods and 2 standard deviations
df['upper_band_20_2'], df['middle_band_20_2'], df['lower_band_20_2'] = talib.BBANDS(
    df['close'], timeperiod=20, nbdevup=2, nbdevdn=2, matype=1)

In [48]:
import pandas as pd
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
from dateutil import parser

# Renaming columns to fit the Backtesting.py requirements
df = df.rename(columns={
    'open': 'Open',
    'high': 'High',
    'low': 'Low',
    'close': 'Close',
    'volume': 'Volume'  
})
# Defining all required strategy classes

# 1. SMA(2,5)
class SMA25Strategy(Strategy):
    def init(self):
        self.sma2 = self.I(lambda x: x, self.data.SMA_2)
        self.sma5 = self.I(lambda x: x, self.data.SMA_5)

    def next(self):
        if crossover(self.sma2, self.sma5):
            if not self.position:
                self.buy()
        elif crossover(self.sma5, self.sma2):
            if self.position:
                self.position.close()

# 2. SMA(5,10)
class SMA510Strategy(Strategy):
    def init(self):
        self.sma5 = self.I(lambda x: x, self.data.SMA_5)
        self.sma10 = self.I(lambda x: x, self.data.SMA_10)

    def next(self):
        if crossover(self.sma5, self.sma10):
            if not self.position:
                self.buy()
        elif crossover(self.sma10, self.sma5):
            if self.position:
                self.position.close()

# 3. RSI(40-60)
class RSI40_60_Strategy(Strategy):
    def init(self):
        self.rsi = self.I(lambda x: x, self.data.RSI_14)

    def next(self):
        if self.rsi[-1] < 40:
            if not self.position:
                self.buy()
        elif self.rsi[-1] > 60:
            if self.position:
                self.position.close()

# 4. MACD (7,21,5)
class MACDStrategy(Strategy):
    def init(self):
        self.macd = self.I(lambda x: x, self.data.MACD)
        self.macd_signal = self.I(lambda x: x, self.data.MACD_Signal)

    def next(self):
        if crossover(self.macd, self.macd_signal):
            if not self.position:
                self.buy()
        elif crossover(self.macd_signal, self.macd):
            if self.position:
                self.position.close()

# 5. Bollinger Bands (20,2)
class BollingerBandsStrategy(Strategy):
    def init(self):
        self.upper_band = self.I(lambda x: x, self.data.upper_band_20_2)
        self.lower_band = self.I(lambda x: x, self.data.lower_band_20_2)

    def next(self):
        if self.data.Close[-1] < self.lower_band[-1]:
            if not self.position:
                self.buy()
        elif self.data.Close[-1] > self.upper_band[-1]:
            if self.position:
                self.position.close()

# 6. SMA-EMA(2,5)
class SMAEMA25Strategy(Strategy):
    def init(self):
        self.sma2 = self.I(lambda x: x, self.data.SMA_2)
        self.ema5 = self.I(lambda x: x, self.data.EMA_5)

    def next(self):
        if crossover(self.sma2, self.ema5):
            if not self.position:
                self.buy()
        elif crossover(self.ema5, self.sma2):
            if self.position:
                self.position.close()

# 7. RSI-MACD
class RSIMACDStrategy(Strategy):
    def init(self):
        self.rsi = self.I(lambda x: x, self.data.RSI_14)
        self.macd = self.I(lambda x: x, self.data.MACD)
        self.macd_signal = self.I(lambda x: x, self.data.MACD_Signal)

    def next(self):
        if self.rsi[-1] < 40 and crossover(self.macd, self.macd_signal):
            if not self.position:
                self.buy()
        elif self.rsi[-1] > 60 or crossover(self.macd_signal, self.macd):
            if self.position:
                self.position.close()

# 8. EMA-BB
class EMABBStrategy(Strategy):
    def init(self):
        self.ema20 = self.I(lambda x: x, self.data.EMA_20)
        self.upper_band = self.I(lambda x: x, self.data.upper_band_20_2)
        self.lower_band = self.I(lambda x: x, self.data.lower_band_20_2)

    def next(self):
        if self.ema20[-1] < self.lower_band[-1]:
            if not self.position:
                self.buy()
        elif self.ema20[-1] > self.upper_band[-1]:
            if self.position:
                self.position.close()

# Defining strategies dictionary
strategies = {
    'SMA_2_5': SMA25Strategy,
    'SMA_5_10': SMA510Strategy,
    'RSI_40_60': RSI40_60_Strategy,
    'MACD': MACDStrategy,
    'BB_20_2': BollingerBandsStrategy,
    'SMA_EMA_2_5': SMAEMA25Strategy,
    'RSI_MACD': RSIMACDStrategy,
    'EMA_BB': EMABBStrategy
}
# Functioning to fetch data for each time frame
def fetch_data_for_time_frame(df, start_date, time_frame):
    if 'min' in time_frame:
        minutes = int(time_frame.replace('min', ''))
        end_date = start_date + pd.Timedelta(minutes=minutes)
    elif 'hr' in time_frame:
        hours = int(time_frame.replace('hr', ''))
        end_date = start_date + pd.Timedelta(hours=hours)
    elif 'week' in time_frame:
        weeks = int(time_frame.replace(' week', ''))
        end_date = start_date + pd.Timedelta(weeks=weeks)
    elif 'day' in time_frame or '24hr' in time_frame:
        days = 1  # Assuming 1 day for 24hr
        end_date = start_date + pd.Timedelta(days=days)
    else:
        print("Unsupported time frame. Please enter a valid time frame (e.g., '15min', '1hr', '4hr', '8hr', '24hr', or '1 week').")
        return None, None

    # Filtering the DataFrame for the specified time range
    mask = (df.index >= start_date) & (df.index < end_date)
    result_df = df.loc[mask]
    return result_df, end_date

# Generalizing function for running and saving backtest
def run_and_save_backtest(strategy_class, df_backtest):
    bt = Backtest(df_backtest, strategy_class, cash=10000, commission=.002, exclusive_orders=True)
    output = bt.run()
    return output

# Functioning to calculate Sharpe Ratio, Annualized Volatility, and Annualized Return
def calculate_metrics(results, periods_per_year):
    metrics = []  # To store results for each timeframe

    for start, end, output in results:
        # Extracting the equity curve
        equity_curve = output['_equity_curve']

        # Calculating returns
        equity_curve['Return'] = equity_curve['Equity'].pct_change()  # Percent change in equity
        returns = equity_curve['Return'].dropna()  # Drop NaN values

        # Calculating cumulative return
        starting_equity = equity_curve['Equity'].iloc[0]
        ending_equity = equity_curve['Equity'].iloc[-1]
        cumulative_return = (ending_equity - starting_equity) / starting_equity

        # Calculating total periods
        total_periods = len(equity_curve)

        # Calculating metrics
        mean_return = returns.mean()
        std_dev = returns.std()
        sharpe_ratio = mean_return / std_dev if std_dev != 0 else 0  # Avoid division by zero
        annualized_sharpe = sharpe_ratio * (periods_per_year ** 0.5)
        annualized_volatility = std_dev * (periods_per_year ** 0.5)
        annualized_return = (1 + cumulative_return) ** (periods_per_year / total_periods) - 1

        # Saving results
        metrics.append({
            'Start': start,
            'End': end,
            'Mean Return': mean_return,
            'Standard Deviation': std_dev,
            'Sharpe Ratio': sharpe_ratio,
            'Annualized Sharpe Ratio': annualized_sharpe,
            'Annualized Volatility': annualized_volatility,
            'Annualized Return': annualized_return,
            'Equity Final [$]': output['Equity Final [$]'],
            '# Trades': output['# Trades']
        })

    return pd.DataFrame(metrics)

# Defining periods per year based on the timeframe
time_frame_mapping = {
    '15min': 525600 / 15,
    '1hr': 8760,
    '4hr': 8760 / 4,
    '8hr': 8760 / 8,
    '24hr': 365,
    '1 week': 52
}



# Main execution
if __name__ == "__main__":
    time_frame = input("Enter the desired time frame (e.g., '15min', '1hr', '4hr', '8hr', '24hr', '1 week'): ").strip()

    if time_frame not in time_frame_mapping:
        print(f"Unsupported timeframe: {time_frame}")
        exit()

    periods_per_year = time_frame_mapping[time_frame]

    results = []
    start_date = df.index.min()
    while start_date < df.index.max():
        filtered_data, end_date = fetch_data_for_time_frame(df, start_date, time_frame)
        if filtered_data is None or filtered_data.empty:
            break
        df_backtest = filtered_data.loc[filtered_data['EMA_5'].first_valid_index():].copy()

        if df_backtest.empty:
            start_date = end_date
            continue

        max_close = df_backtest['Close'].max()
        target_max_price = 100
        scale_factor = max_close / target_max_price

        df_backtest['Open'] /= scale_factor
        df_backtest['High'] /= scale_factor
        df_backtest['Low'] /= scale_factor
        df_backtest['Close'] /= scale_factor

        for name, strategy in strategies.items():
            output = run_and_save_backtest(strategy, df_backtest)
            results.append((start_date, end_date, output, name))

        start_date = end_date

    # Processing and saving results for each strategy
    for strategy_name in strategies.keys():
        # Extracting results for the strategy
        strategy_results = [(start, end, output) for start, end, output, name in results if name == strategy_name]

        # Filtering results with more than 1 trade
        results_with_trades = [(start, end, output) for start, end, output in strategy_results if output['# Trades'] > 1]

        # Sorting by Equity Final [$] in descending order
        sorted_results = sorted(results_with_trades, key=lambda x: x[2]['Equity Final [$]'], reverse=True)[:3]  # Top 3

        # Calculating metrics
        metrics = calculate_metrics(sorted_results, periods_per_year)

        # Saving to CSV
        metrics.to_csv(f'{strategy_name}_metrics.csv', index=False)

        print(f"Saved top 3 trades with metrics for {strategy_name} to {strategy_name}_metrics.csv")

Enter the desired time frame (e.g., '15min', '1hr', '4hr', '8hr', '24hr', '1 week'):  1 week

C:\Users\ganes\AppData\Local\Programs\Python\Python312\Lib\site-packages\backtesting\_stats.py:122: RuntimeWarning: divide by zero encountered in scalar divide
  s.loc['Sortino Ratio'] = np.clip((annualized_return - risk_free_rate) / (np.sqrt(np.mean(day_returns.clip(-np.inf, 0)**2)) * np.sqrt(annual_trading_days)), 0, np.inf)  # noqa: E501

Saved top 3 trades with metrics for SMA_2_5 to SMA_2_5_metrics.csv
Saved top 3 trades with metrics for SMA_5_10 to SMA_5_10_metrics.csv
Saved top 3 trades with metrics for RSI_40_60 to RSI_40_60_metrics.csv
Saved top 3 trades with metrics for MACD to MACD_metrics.csv
Saved top 3 trades with metrics for BB_20_2 to BB_20_2_metrics.csv
Saved top 3 trades with metrics for SMA_EMA_2_5 to SMA_EMA_2_5_metrics.csv
Saved top 3 trades with metrics for RSI_MACD to RSI_MACD_metrics.csv
Saved top 3 trades with metrics for EMA_BB to EMA_BB_metrics.csv